### ISSUE TITLE
empty report if there are no xml's to proceed

### ISSUE THREAD

**Issue by mavlyutov** [allure-framework/allure-teamcity-plugin#16]
steps to reproduce:
1. create empty teamcity build_configuration
2. add allure report generation as build feature
3. run build_configuration

as a result one will receive empty allure report

is this a bug? 
or maybe we should push warn message to build log that there is no xml's to proceed?

**Comment by vania-pooh** [comment]
@eroshenkoam thoughts?

**Comment by baev** [comment]
The same https://github.com/allure-framework/allure-core/issues/595

I propose to fail report generation if no results found.

**Comment by baev** [comment]
since 1.4.15 report generation will fall if no results found in specified directories
