### ISSUE TITLE
plugin tries to collect xml's after each build step

### ISSUE THREAD

**Issue by mavlyutov** [allure-framework/allure-teamcity-plugin#17]
steps to reproduce:
1. create an empty build_configuration
2. add two or more dummy build steps
3. turn on allure report generation

as a result, in build log you can see as miserable allure-plugin attempts to collect xml's after each build step
in comparison to above-written behavior, junit report processor collects files only after full build_configuration run

**Comment by vania-pooh** [comment]
Duplicates #13. Fixed but not released yet.
