### ISSUE TITLE
Empty allure report

### ISSUE THREAD

**Issue by alice-kalashnikova** [allure-framework/allure-teamcity-plugin#21]
Allure plugin is set up according to instruction: https://github.com/allure-framework/allure-teamcity-plugin, but as a result we have empty report though xml files are correct with data.
In Results Directories I put path to allure-results.
Command 'mvn site' is a separate step in build steps.
Other information:
Report Version - 1.4.11
TeamCity - 8.1

**Comment by eroshenkoam** [comment]
Fixed
