### ISSUE TITLE
There is no allure.issues.tracker.pattern value on build feature interface

### ISSUE THREAD

**Issue by SlimBim** [allure-framework/allure-teamcity-plugin#22]
Please, add allure.issues.tracker.pattern to build feature interface.

**Comment by SlimBim** [comment]
Hi guys.
Any updates about this ticket?

**Comment by baev** [comment]
Hi. Feel free to send us pull request

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-teamcity-plugin/pull/28 . The release and documentation is coming soon.
