### ISSUE TITLE
Plugins doesn't work on Windows

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-teamcity-plugin#30]
Error: Could not find or load main class ru.yandex.qatools.allure.CommandLine

**Comment by baev** [comment]
closed via #31

**Comment by pdoggyster** [comment]
Hi, 
When it will be released?

**Comment by baev** [comment]
@pdoggyster sorry for the delay I'll release it ASAP

**Comment by pdoggyster** [comment]
I'm looking forward to it.

**Comment by baev** [comment]
https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/allure-teamcity-plugin-2.2
