### ISSUE TITLE
Not possible to enter "**/" in Allure result directory

### ISSUE THREAD

**Issue by sergmal** [allure-framework/allure-teamcity-plugin#33]
TeamCity version 9.1.1
Allure version 1.4.19

TeamCity-> Build Steps-> Allure report:

By default there is Allure results directory: "allure-results/"
When I enter "**/allure-results/" i will get an error message from browser Error accessing server, cannot read property "documentElement" of null
When i enter full url without asteriks, then everything is saved correctly

**Comment by baev** [comment]
@sergmal thanks for suggestion! 

There is no more ability to specify the pattern. Why are you need such feature?

**Comment by sergmal** [comment]
Thank you for info. 

"projectname/target/allure-results/" is now working for me. 

Please close this ticket then

**Comment by baev** [comment]
@sergmal glad to hear
