### ISSUE TITLE
Location allure report configurable in artifacts directory

### ISSUE THREAD

**Issue by ThaStealth** [allure-framework/allure-teamcity-plugin#34]
Teamcity plugin collects the artifacts generated by Allure and puts them in the root directory of the artifacts. Since we configured teamcity to also put the .exe and .dll files of the application overthere it gets a little messy.
Can it be made possible to configure the plugin to put it in a subdir in the artifacts output? The Reports tab seems to be able to handle this in Teamcity.

**Comment by baev** [comment]
@ThaStealth sorry for the delay. Fixed via #37

**Comment by baev** [comment]
https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/allure-teamcity-plugin-2.3
