### ISSUE TITLE
Plugin 2.2 TeamCity 9.0.1: Incompatible runner: Allure Report

### ISSUE THREAD

**Issue by teknogecko** [allure-framework/allure-teamcity-plugin#35]
Just installed Allure TeamCity plugin version 2.2 on TeamCity 9.0.1. 

I see the plugin has unzipped in the TeamCity and Agent folders, but the Agents keep reporting "Incompatible runner: Allure Report". Even after several full restarts.

team-agent.log:
`[2015-11-19 12:38:54,428]   INFO - rver.plugins.PluginManagerImpl - Loaded 57 plugins: [agentSystemInfo, allure-teamcity-plugin-agent, amazonEC2, ant, ant-net-tasks, antPlugin, assembly-info-patcher, clearcase-agent, commandLineRunner, coveragePlugin, crashDetector, cvsAgent, dotCover, dotnet-tools, dotnetPlugin, dotNetRunners, duplicatePlugin, environment-fetcher, fxcop, gant, gantPlugin, gradle-runner, idea, idea-runner, inspectionPlugin, ipr-runner, jacoco, java-dowser, jetbrains.git, jps, jps-old, junitPlugin, jvm-update, maven, maven3, maven3_1, maven3_2, mavenPlugin, mercurial, meta-runner, nuget-agent, NuGet.CommandLine.2.8.6.nupkg, NuGet.CommandLine.DEFAULT.nupkg, perfmon, perforce-agent, powershell-agent, rake-runner, remoteAccess, ssh-manager, stacktracesPlugin, svnAgent, swabra, SysinternalsHandle, testNGPlugin, tfs-agent, xcode-runner, xml-report-plugin] `

As you can see the "allure-teamcity-plugin-agent" plugin seems to be loaded.

**Comment by baev** [comment]
@teknogecko hi! You also need to install `allure-commandline`. See step 2 from installation section http://wiki.qatools.ru/display/AL/Allure+TeamCity+Plugin

**Comment by teknogecko** [comment]
Right... missed that one... thanks! ;-)

**Comment by teknogecko** [comment]
Hi, I'm stuck again... I've managed to generate the trx file MSTest, then convert it to Xml with the MSTestAllureAdapter, but the report step generates this error: 

Error: Could not find or load main class ru.yandex.qatools.allure.AllureMain.

`[16:28:39]Step 7/7: Generate Report (Allure Report)`
`[16:28:39][Step 7/7] Starting: C:\TeamCity\jre\bin\java.exe -Dallure.config=C:\TeamCity\buildAgent\temp\buildTmp\allure-config8054267216528330979\allure.properties -Dallure.home=C:\TeamCity\buildAgent\tools\allure-commandline -classpath C:\TeamCity\buildAgent\tools\allure-commandline\lib/*;C:\TeamCity\buildAgent\tools\allure-commandline\conf ru.yandex.qatools.allure.CommandLine -v generate C:\TeamCity\buildAgent\work\b61432085ed25452\results --output C:\TeamCity\buildAgent\temp\buildTmp\allure-report2432461476451923049`
`[16:28:39][Step 7/7] in directory: C:\TeamCity\buildAgent\work\b61432085ed25452`
`[16:28:39][Step 7/7] Error: Could not find or load main class ru.yandex.qatools.allure.AllureMain`
`[16:28:39][Step 7/7]  [0;31mERROR: [mCommand aborted due to exception org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1).`
`[16:28:39][Step 7/7] Process exited with code 1`
`[16:28:40][Step 7/7] Step Generate Report (Allure Report) failed`

All folders seem to be ok.

**Comment by baev** [comment]
could you please show me the content of `C:\TeamCity\buildAgent\tools\allure-commandline\lib` folder?

**Comment by teknogecko** [comment]
Here we go:
> airline.jar
allure-commandline.jar
cal10n-api.jar
commons-exec.jar
gson.jar
guava.jar
javax.inject.jar
javax.servlet-api.jar
jetty-http.jar
jetty-io.jar
jetty-server.jar
jetty-util.jar
jsr305.jar
list.txt
log4j.jar
properties.jar
retrofit.jar
slf4j-api.jar
slf4j-ext.jar
slf4j-log4j12.jar

**Comment by teknogecko** [comment]
Found anything?

**Comment by baev** [comment]
@teknogecko sorry, I missed this one. Could you please specify your OS version? Win 10 latest all works fine

**Comment by teknogecko** [comment]
Windows Server 2012 R2 Standard

**Comment by DimaDubyk** [comment]
Possible reason may be old java version

**Comment by teknogecko** [comment]
Which version do you recommend?

**Comment by baev** [comment]
I suggest you to use Allure Commandline 1.4.20, all should be fine now. Required java version is 1.7  or later

**Comment by DimaDubyk** [comment]
For me solution was to update Teamcity agents from old version (older than 8.1.2) to latest 9.1.3.
It was surprise for me that teamcity doesn't upgrade agents after upgrade TC server

**Comment by teknogecko** [comment]
I'm now at TC 9.1.4 with Java 1.8. Will give it a go next week. Busy with releases at work.

**Comment by anuvratashu** [comment]
I have TC 9.1.7 and Java 1.7. However, the error is still comming up
Incompatible runner: Allure Report
not sure how to add the allure reporting to the Teamcity.

if i remove the Allure Report then the build runs fine.
![image](https://cloud.githubusercontent.com/assets/14295329/16006434/b8dc1a66-318a-11e6-8c9f-aeddc1255f6f.png)

**Comment by DITLPANW** [comment]
@baev, 
Hi, Can you please explain how to install the "allure-commandline" on agent ?
10x

**Comment by baev** [comment]
@DITLPANW please use our Gitter https://gitter.im/allure-framework/allure-core / StackOverflow tag allure for such questions
