### ISSUE TITLE
Generate allure files to separate folder in artifacts

### ISSUE THREAD

**Issue by artkoshelev** [allure-framework/allure-teamcity-plugin#38]

**Comment by vania-pooh** [comment]
@artkoshelev хау эбаут мор дитеилз?

**Comment by theyoprst** [comment]
@vania-pooh я могу рассказать :) Сейчас плагин льет все свои артефакты в корень, они смешиваются с уже существующими и получается каша. Хочется иметь настройку, в которой можно сказать, где создавать артефакты.

**Comment by baev** [comment]
https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/allure-teamcity-plugin-2.3

**Comment by baev** [comment]
https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/allure-teamcity-plugin-2.3

**Comment by baev** [comment]
https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/allure-teamcity-plugin-2.3

**Comment by theyoprst** [comment]
Спасибо!
