### ISSUE TITLE
Pick up latest result of the re-runned test

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-teamcity-plugin#41]
Hey guys, 

Currently we started to use maven-surefire-plugin with -Dsurefire.rerunFailingTestsCount=1 -D.surefire.skipAfterFailureCount=10 flags. 

The problem we faced is that now in Allure report for failed tests i see two same records 
<img width="1342" alt="screenshot 2016-03-24 10 45 49" src="https://cloud.githubusercontent.com/assets/1200012/14013669/fd479026-f1ad-11e5-922a-5f507c7f8304.png">

which are basically duplicates for the same failure. Is there an easy way to get only latest failure result and show one line ?

**Comment by baev** [comment]
@azakordonets hi

> Is there an easy way to get only latest failure result and show one line ?

Nope. Allure doesn't know is it a retry or not at this point. 

We are working on retry feature for Allure Report 2.0. And I don't see any ways to fix it for now.

**Comment by azakordonets** [comment]
Ok, got it. Will wait for 2.0 then. Thanks for quick reply
