### ISSUE TITLE
Allure Attachments are downloaded to disk instead of being displayed in Team City

### ISSUE THREAD

**Issue by Metaun** [allure-framework/allure-teamcity-plugin#43]
I am using the latest version Allure Report 1.4.24.RC3 and use TeamCity 10. 
What could be the problem?

**Comment by baev** [comment]
Hi! Thanks for the report. Could you please give a little bit more information about the problem?

**Comment by Metaun** [comment]
Hi!
To failed tests are attached screenshots and by clicking on the screenshots it is loaded onto my computer as a regular file, and does not appear in the browser as usual.
For example :
Should be (it if i run report local with jetty)
http://prntscr.com/bz5gv7

But in TeamCity I see this 
http://prntscr.com/bz5hws
(if I click on "Page screenshot" it just download on my local disk)

**Comment by baev** [comment]
As far as I can see the problem with your attachment type. Images have [file-image-o](http://fontawesome.io/icon/file-image-o/) icon.

**Comment by Metaun** [comment]
Hm, I use  "image/png" type, nothing special

**Comment by Metaun** [comment]
Sorry, reason was my carelessness :)
I used "images/png" instead of "image/png" in attachment type.
Thanks!
